export enum ActionType {
  CREATE = 'CREATE',
  UPDATE_COMPLETED = 'UPDATE_COMPLETED',
  UPDATE_DUE_DATE = 'UPDATE_DUE_DATE',
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
}

